#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jan 25, 2022 03:00:47 PM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 793x615+701+346
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 333 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 373 
    vTcl:DefineAlias "$top.can46" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can47 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 86 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 225 
    vTcl:DefineAlias "$top.can47" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can48 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 44 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 747 
    vTcl:DefineAlias "$top.can48" "Canvas3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can48
    text $site_3_0.tex65 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 94 -wrap word 
    $site_3_0.tex65 configure -font "TkTextFont"
    $site_3_0.tex65 insert end text
    vTcl:DefineAlias "$site_3_0.tex65" "Text1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tex65 \
        -in $site_3_0 -x 0 -relx 0.415 -y 0 -rely 0.227 -width 0 \
        -relwidth 0.126 -height 0 -relheight 0.545 -anchor nw \
        -bordermode ignore 
    canvas $top.can49 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 138 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 225 
    vTcl:DefineAlias "$top.can49" "Canvas4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can49
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #00b300 \
        -background #05c100 -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but51" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but52" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but53" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but54" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but55" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but56" "Button6" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.182 -y 0 -rely 0.087 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.578 -y 0 -rely 0.072 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.178 -y 0 -rely 0.362 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.178 -y 0 -rely 0.652 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.578 -y 0 -rely 0.362 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.578 -y 0 -rely 0.652 -width 57 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    canvas $top.can59 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 123 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 226 
    vTcl:DefineAlias "$top.can59" "Canvas5" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can60 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 80 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 226 
    vTcl:DefineAlias "$top.can60" "Canvas6" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can60
    button $site_3_0.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Reset Cube} 
    vTcl:DefineAlias "$site_3_0.but61" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Generate Solution} 
    vTcl:DefineAlias "$site_3_0.but62" "Button8" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but61 \
        -in $site_3_0 -x 0 -relx 0.31 -y 0 -rely 0.125 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.15 -y 0 -rely 0.5 -width 157 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    canvas $top.can63 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 63 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 493 
    vTcl:DefineAlias "$top.can63" "Canvas7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Button 
    vTcl:DefineAlias "$top.but64" "Button9" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can46 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.114 -width 0 -relwidth 0.622 \
        -height 0 -relheight 0.74 -anchor nw -bordermode ignore 
    place $top.can47 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.111 -width 0 -relwidth 0.284 \
        -height 0 -relheight 0.14 -anchor nw -bordermode ignore 
    place $top.can48 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.016 -width 0 -relwidth 0.942 \
        -height 0 -relheight 0.072 -anchor nw -bordermode ignore 
    place $top.can49 \
        -in $top -x 0 -relx 0.681 -y 0 -rely 0.26 -width 0 -relwidth 0.284 \
        -height 0 -relheight 0.224 -anchor nw -bordermode ignore 
    place $top.can59 \
        -in $top -x 0 -relx 0.681 -y 0 -rely 0.504 -width 0 -relwidth 0.285 \
        -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $top.can60 \
        -in $top -x 0 -relx 0.681 -y 0 -rely 0.715 -width 0 -relwidth 0.285 \
        -height 0 -relheight 0.13 -anchor nw -bordermode ignore 
    place $top.can63 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.878 -width 0 -relwidth 0.622 \
        -height 0 -relheight 0.102 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.681 -y 0 -rely 0.878 -width 227 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

